sudo: false
notifications:
  email: false
language: python
matrix:
  include:
    - python: "2.7"
      env: "COVERAGE=1"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      env: "COVERAGE=1"
    - python: "3.8"
    - python: "nightly"
  allow_failures:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "nightly"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
services:
  - mysql
before_script:
  - mysql -e 'create database trapp;'
  - sh -c "mysql < tests/fixtures/lkp_matchtypes.sql"
  - sh -c "mysql < tests/fixtures/lnk_players_combos.sql"
  - sh -c "mysql < tests/fixtures/tbl_combos.sql"
  - sh -c "mysql < tests/fixtures/tbl_combos_stats.sql"
  - sh -c "mysql < tests/fixtures/tbl_gameevents.sql"
  - sh -c "mysql < tests/fixtures/tbl_gameminutes.sql"
  - sh -c "mysql < tests/fixtures/tbl_gamestats.sql"
  - sh -c "mysql < tests/fixtures/tbl_games.sql"
  - sh -c "mysql < tests/fixtures/tbl_players.sql"
  - sh -c "mysql < tests/fixtures/tbl_teams.sql"
  - sh -c "mysql < tests/fixtures/tbl_venues.sql"
  - sh -c "mysql < tests/fixtures/test_data.sql"
script:
  - coverage run --source=trapp -m pytest tests/
after_script:
  - if [[ "$COVERAGE" == "1" ]]; then coveralls; fi
