sudo: false
notifications:
  email: false
language: python
env:
  - TOX_ENV=py27
  - TOX_ENV=py36
  - TOX_ENV=coveralls
install:
  - pip install tox
services:
  - mysql
before_script:
  - mysql -e 'create database trapp;'
  - sh -c "mysql < tests/fixtures/lkp_matchtypes.sql"
  - sh -c "mysql < tests/fixtures/lnk_players_combos.sql"
  - sh -c "mysql < tests/fixtures/tbl_combos.sql"
  - sh -c "mysql < tests/fixtures/tbl_combos_stats.sql"
  - sh -c "mysql < tests/fixtures/tbl_gameevents.sql"
  - sh -c "mysql < tests/fixtures/tbl_gameminutes.sql"
  - sh -c "mysql < tests/fixtures/tbl_gamestats.sql"
  - sh -c "mysql < tests/fixtures/tbl_games.sql"
  - sh -c "mysql < tests/fixtures/tbl_players.sql"
  - sh -c "mysql < tests/fixtures/tbl_teams.sql"
  - sh -c "mysql < tests/fixtures/tbl_venues.sql"
  - sh -c "mysql < tests/fixtures/test_data.sql"
script:
  - tox -e $TOX_ENV
