sudo: false
notifications:
  email: false
language: python
env:
  - TOX_ENV=py27
  - TOX_ENV=coveralls
install:
  - pip install tox
services:
  - mysql
before_script:
  - mysql -e 'create database trapp;'
  - sh -c "mysql -e 'CREATE TABLE trapp.tbl_games (
    ID int(11) NOT NULL AUTO_INCREMENT,
    MatchTime datetime DEFAULT NULL,
    MatchTypeID int(10) unsigned NOT NULL DEFAULT 0,
    HteamID int(11) DEFAULT NULL,
    Hscore int(11) DEFAULT 0,
    AteamID int(11) DEFAULT NULL,
    Ascore int(11) DEFAULT 0,
    VenueID int(11) DEFAULT NULL,
    Duration int(11) unsigned NOT NULL DEFAULT 0,
    Attendance int(11) DEFAULT NULL,
    MeanTemperature int(3) unsigned DEFAULT NULL,
    Precipitation double(2,1) DEFAULT NULL,
    WeatherEvents varchar(255) DEFAULT NULL,
    Notes text,
    PRIMARY KEY (ID)
    ) ENGINE=MyISAM AUTO_INCREMENT=17216 DEFAULT CHARSET=utf8;'"
  - sh -c "mysql < tests/fixtures/tbl_players.sql"
script:
  - tox -e $TOX_ENV
